const fakeData = [
  {
    label: 'week1',
    SUGARS: 50,
    FAT: 60,
    PROTEIN: 20,
    CARBO: 50,
    SODIUM: 50,
    CALORIES: 50,
  },
  {
    label: 'week2',
    SUGARS: 40,
    FAT: 60,
    PROTEIN: 70,
    CARBO: 50,
    SODIUM: 40,
    CALORIES: 50,
  },
  {
    label: 'Week3',
    SUGARS: 50,
    FAT: 60,
    PROTEIN: 25,
    CARBO: 50,
    SODIUM: 40,
    CALORIES: 50,
  },
  {
    label: 'Week4',
    SUGARS: 50,
    FAT: 60,
    PROTEIN: 20,
    CARBO: 60,
    SODIUM: 50,
    CALORIES: 50,
  },
];

// const fakeData = [
//   {
//     mtl_id: 1,
//     mtl_week: 'week1',
//     mtl_name: ['醋飯', '醋飯', '鮭魚', '鮪魚', '鮪魚'],
//   },
//   {
//     mtl_id: 3,
//     mtl_week: 'week2',
//     mtl_name: '鮪魚',
//     mtl_sugar: 0,
//     mtl_oil: 1,
//     mtl_protein: 31,
//     mtl_carbo: 0,
//     mtl_na: 1,
//     mtl_calories: 20,
//   },
//   {
//     mtl_id: 4,
//     mtl_name: '比目魚',
//     mtl_week: 'week2',
//     mtl_sugar: 0,
//     mtl_oil: 2,
//     mtl_protein: 29,
//     mtl_carbo: 0,
//     mtl_na: 0,
//     mtl_calories: 20,
//   },
//   {
//     mtl_id: 4,
//     mtl_name: '比目魚',
//     mtl_week: 'week3',
//     mtl_sugar: 0,
//     mtl_oil: 2,
//     mtl_protein: 29,
//     mtl_carbo: 0,
//     mtl_na: 0,
//     mtl_calories: 20,
//   },
//   {
//     mtl_id: 4,
//     mtl_name: '比目魚',
//     mtl_week: 'week3',
//     mtl_sugar: 0,
//     mtl_oil: 2,
//     mtl_protein: 29,
//     mtl_carbo: 0,
//     mtl_na: 0,
//     mtl_calories: 20,
//   },
//   {
//     mtl_id: 5,
//     mtl_name: '烏賊',
//     mtl_week: 'week4',
//     mtl_sugar: 0,
//     mtl_oil: 1,
//     mtl_protein: 15,
//     mtl_carbo: 0,
//     mtl_na: 1,
//     mtl_calories: 20,
//   },
//   {
//     mtl_id: 6,
//     mtl_name: '花枝',
//     mtl_week: 'week4',
//     mtl_sugar: 0,
//     mtl_oil: 1,
//     mtl_protein: 15,
//     mtl_carbo: 0,
//     mtl_na: 0,
//     mtl_calories: 20,
//   },
//   {
//     mtl_id: 6,
//     mtl_name: '花枝',
//     mtl_week: 'week4',
//     mtl_sugar: 0,
//     mtl_oil: 1,
//     mtl_protein: 15,
//     mtl_carbo: 0,
//     mtl_na: 0,
//     mtl_calories: 20,
//   },
// ];

export default fakeData;
