const nuData = [
  {
    mtl_id: 1,
    mtl_name: '醋飯',
    mtl_sugar: 3,
    mtl_oil: 20,
    mtl_protein: 20,
    mtl_carbo: 20,
    mtl_na: 0,
    mtl_calories: 25,
  },
  {
    mtl_id: 2,
    mtl_name: '鮭魚',
    mtl_sugar: 10,
    mtl_oil: 17,
    mtl_protein: 30,
    mtl_carbo: 3,
    mtl_na: 10,
    mtl_calories: 25,
  },
  {
    mtl_id: 3,
    mtl_name: '鮪魚',
    mtl_sugar: 5,
    mtl_oil: 14,
    mtl_protein: 31,
    mtl_carbo: 10,
    mtl_na: 20,
    mtl_calories: 20,
  },
  {
    mtl_id: 4,
    mtl_name: '比目魚',
    mtl_sugar: 0,
    mtl_oil: 9,
    mtl_protein: 29,
    mtl_carbo: 36,
    mtl_na: 30,
    mtl_calories: 5,
  },
  {
    mtl_id: 5,
    mtl_name: '烏賊',
    mtl_sugar: 10,
    mtl_oil: 10,
    mtl_protein: 15,
    mtl_carbo: 33,
    mtl_na: 40,
    mtl_calories: 20,
  },
  {
    mtl_id: 6,
    mtl_name: '花枝',
    mtl_sugar: 15,
    mtl_oil: 3,
    mtl_protein: 15,
    mtl_carbo: 30,
    mtl_na: 15,
    mtl_calories: 20,
  },
  {
    mtl_id: 7,
    mtl_name: '章魚',
    mtl_sugar: 5,
    mtl_oil: 6,
    mtl_protein: 20,
    mtl_carbo: 27,
    mtl_na: 25,
    mtl_calories: 5,
  },
  {
    mtl_id: 8,
    mtl_name: '玉子',
    mtl_sugar: 10,
    mtl_oil: 9,
    mtl_protein: 15,
    mtl_carbo: 24,
    mtl_na: 35,
    mtl_calories: 10,
  },
  {
    mtl_id: 9,
    mtl_name: '蟹棒',
    mtl_sugar: 0,
    mtl_oil: 12,
    mtl_protein: 15,
    mtl_carbo: 21,
    mtl_na: 5,
    mtl_calories: 12,
  },
  {
    mtl_id: 10,
    mtl_name: '鮮蝦',
    mtl_sugar: 5,
    mtl_oil: 15,
    mtl_protein: 29,
    mtl_carbo: 18,
    mtl_na: 10,
    mtl_calories: 15,
  },
  {
    mtl_id: 11,
    mtl_name: '甜蝦',
    mtl_sugar: 7,
    mtl_oil: 20,
    mtl_protein: 30,
    mtl_carbo: 15,
    mtl_na: 15,
    mtl_calories: 15,
  },
  {
    mtl_id: 12,
    mtl_name: '秋刀魚',
    mtl_sugar: 5,
    mtl_oil: 18,
    mtl_protein: 29,
    mtl_carbo: 12,
    mtl_na: 20,
    mtl_calories: 10,
  },
  {
    mtl_id: 13,
    mtl_name: '星鰻',
    mtl_sugar: 10,
    mtl_oil: 15,
    mtl_protein: 30,
    mtl_carbo: 9,
    mtl_na: 30,
    mtl_calories: 30,
  },
  {
    mtl_id: 14,
    mtl_name: '鯖魚',
    mtl_sugar: 5,
    mtl_oil: 12,
    mtl_protein: 15,
    mtl_carbo: 6,
    mtl_na: 5,
    mtl_calories: 5,
  },
  {
    mtl_id: 15,
    mtl_name: '牛排',
    mtl_sugar: 15,
    mtl_oil: 9,
    mtl_protein: 32,
    mtl_carbo: 3,
    mtl_na: 40,
    mtl_calories: 20,
  },
  {
    mtl_id: 16,
    mtl_name: '雞排',
    mtl_sugar: 10,
    mtl_oil: 6,
    mtl_protein: 29,
    mtl_carbo: 36,
    mtl_na: 35,
    mtl_calories: 5,
  },
  {
    mtl_id: 17,
    mtl_name: '竹筴魚',
    mtl_sugar: 5,
    mtl_oil: 3,
    mtl_protein: 15,
    mtl_carbo: 33,
    mtl_na: 30,
    mtl_calories: 20,
  },
  {
    mtl_id: 18,
    mtl_name: '鰤魚',
    mtl_sugar: 5,
    mtl_oil: 2,
    mtl_protein: 32,
    mtl_carbo: 30,
    mtl_na: 25,
    mtl_calories: 20,
  },
  {
    mtl_id: 19,
    mtl_name: '鯛魚',
    mtl_sugar: 15,
    mtl_oil: 6,
    mtl_protein: 15,
    mtl_carbo: 27,
    mtl_na: 20,
    mtl_calories: 20,
  },
  {
    mtl_id: 20,
    mtl_name: '玉米',
    mtl_sugar: 10,
    mtl_oil: 9,
    mtl_protein: 10,
    mtl_carbo: 10,
    mtl_na: 15,
    mtl_calories: 10,
  },
  {
    mtl_id: 21,
    mtl_name: '叉燒',
    mtl_sugar: 15,
    mtl_oil: 12,
    mtl_protein: 30,
    mtl_carbo: 24,
    mtl_na: 1,
    mtl_calories: 30,
  },
  {
    mtl_id: 22,
    mtl_name: '起司',
    mtl_sugar: 5,
    mtl_oil: 15,
    mtl_protein: 5,
    mtl_carbo: 21,
    mtl_na: 10,
    mtl_calories: 28,
  },
  {
    mtl_id: 23,
    mtl_name: '美乃滋',
    mtl_sugar: 10,
    mtl_oil: 18,
    mtl_protein: 30,
    mtl_carbo: 30,
    mtl_na: 5,
    mtl_calories: 28,
  },
  {
    mtl_id: 24,
    mtl_name: '茄子',
    mtl_sugar: 0,
    mtl_oil: 20,
    mtl_protein: 15,
    mtl_carbo: 18,
    mtl_na: 35,
    mtl_calories: 5,
  },
  {
    mtl_id: 25,
    mtl_name: '羅勒醬',
    mtl_sugar: 0,
    mtl_oil: 18,
    mtl_protein: 5,
    mtl_carbo: 15,
    mtl_na: 30,
    mtl_calories: 20,
  },
  {
    mtl_id: 26,
    mtl_name: '烏魚子',
    mtl_sugar: 5,
    mtl_oil: 15,
    mtl_protein: 29,
    mtl_carbo: 29,
    mtl_na: 25,
    mtl_calories: 20,
  },
  {
    mtl_id: 27,
    mtl_name: '干貝',
    mtl_sugar: 10,
    mtl_oil: 12,
    mtl_protein: 15,
    mtl_carbo: 12,
    mtl_na: 20,
    mtl_calories: 20,
  },
  {
    mtl_id: 28,
    mtl_name: '小黃瓜',
    mtl_sugar: 0,
    mtl_oil: 9,
    mtl_protein: 30,
    mtl_carbo: 30,
    mtl_na: 15,
    mtl_calories: 5,
  },
  {
    mtl_id: 29,
    mtl_name: '山藥',
    mtl_sugar: 10,
    mtl_oil: 3,
    mtl_protein: 5,
    mtl_carbo: 5,
    mtl_na: 10,
    mtl_calories: 20,
  },
  {
    mtl_id: 30,
    mtl_name: '飛魚卵',
    mtl_sugar: 0,
    mtl_oil: 6,
    mtl_protein: 10,
    mtl_carbo: 9,
    mtl_na: 5,
    mtl_calories: 20,
  },
  {
    mtl_id: 31,
    mtl_name: '鮭魚卵',
    mtl_sugar: 10,
    mtl_oil: 9,
    mtl_protein: 15,
    mtl_carbo: 3,
    mtl_na: 40,
    mtl_calories: 5,
  },
  {
    mtl_id: 32,
    mtl_name: '山葵',
    mtl_sugar: 5,
    mtl_oil: 12,
    mtl_protein: 5,
    mtl_carbo: 36,
    mtl_na: 35,
    mtl_calories: 20,
  },
  {
    mtl_id: 33,
    mtl_name: '山葵',
    mtl_sugar: 10,
    mtl_oil: 15,
    mtl_protein: 5,
    mtl_carbo: 33,
    mtl_na: 30,
    mtl_calories: 20,
  },
  {
    mtl_id: 34,
    mtl_name: '蔥',
    mtl_sugar: 0,
    mtl_oil: 18,
    mtl_protein: 5,
    mtl_carbo: 30,
    mtl_na: 25,
    mtl_calories: 5,
  },
  {
    mtl_id: 35,
    mtl_name: '蘿蔔泥',
    mtl_sugar: 10,
    mtl_oil: 20,
    mtl_protein: 0,
    mtl_carbo: 28,
    mtl_na: 20,
    mtl_calories: 20,
  },
  {
    mtl_id: 36,
    mtl_name: '明太子',
    mtl_sugar: 5,
    mtl_oil: 18,
    mtl_protein: 15,
    mtl_carbo: 15,
    mtl_na: 15,
    mtl_calories: 20,
  },
  {
    mtl_id: 37,
    mtl_name: '檸檬片',
    mtl_sugar: 1,
    mtl_oil: 15,
    mtl_protein: 0,
    mtl_carbo: 9,
    mtl_na: 10,
    mtl_calories: 5,
  },
  {
    mtl_id: 38,
    mtl_name: '紅蘿蔔',
    mtl_sugar: 11,
    mtl_oil: 12,
    mtl_protein: 10,
    mtl_carbo: 12,
    mtl_na: 5,
    mtl_calories: 10,
  },
  {
    mtl_id: 39,
    mtl_name: '地瓜',
    mtl_sugar: 1,
    mtl_oil: 9,
    mtl_protein: 10,
    mtl_carbo: 20,
    mtl_na: 40,
    mtl_calories: 10,
  },
  {
    mtl_id: 40,
    mtl_name: '馬鈴薯',
    mtl_sugar: 10,
    mtl_oil: 6,
    mtl_protein: 15,
    mtl_carbo: 15,
    mtl_na: 35,
    mtl_calories: 5,
  },
  {
    mtl_id: 41,
    mtl_name: '秋葵',
    mtl_sugar: 15,
    mtl_oil: 1,
    mtl_protein: 10,
    mtl_carbo: 10,
    mtl_na: 30,
    mtl_calories: 10,
  },
  {
    mtl_id: 42,
    mtl_name: '海苔',
    mtl_sugar: 10,
    mtl_oil: 3,
    mtl_protein: 15,
    mtl_carbo: 22,
    mtl_na: 25,
    mtl_calories: 20,
  },
  {
    mtl_id: 43,
    mtl_name: '紫蘇',
    mtl_sugar: 15,
    mtl_oil: 11,
    mtl_protein: 15,
    mtl_carbo: 25,
    mtl_na: 20,
    mtl_calories: 20,
  },
  {
    mtl_id: 44,
    mtl_name: '番茄',
    mtl_sugar: 15,
    mtl_oil: 14,
    mtl_protein: 10,
    mtl_carbo: 6,
    mtl_na: 15,
    mtl_calories: 10,
  },
  {
    mtl_id: 45,
    mtl_name: '豬肉',
    mtl_sugar: 10,
    mtl_oil: 17,
    mtl_protein: 32,
    mtl_carbo: 3,
    mtl_na: 10,
    mtl_calories: 5,
  },
  {
    mtl_id: 46,
    mtl_name: '香菇',
    mtl_sugar: 5,
    mtl_oil: 20,
    mtl_protein: 10,
    mtl_carbo: 10,
    mtl_na: 5,
    mtl_calories: 10,
  },
];

export default nuData;
